#
# Cookbook Name:: centos-cloud
# Recipe:: keystone-credentials
#
# Copyright 2013, cloudtechlab
#
# All rights reserved - Do Not Redistribute
#
include_recipe "libcloud"

libcloud_file_append "/root/.bashrc" do
        line ["# Keystone credentials. Generated by chef.",
              "export OS_USERNAME=admin",
              "export OS_TENANT_NAME=admin",
              "export OS_PASSWORD=#{node[:creds][:admin_password]}",
              "export OS_AUTH_URL=http://#{node[:ip][:keystone]}:35357/v2.0/"]
end
